---
- hosts: docker
  become: no
  tasks:
  - name: current directory
    shell: pwd
    register: pwd

  - name: Ansible check directory.
    stat:
     path: /tmp/django-pipeline2
    register: my_folder
  
  - name: create directory
    file:
      path: /tmp/django-pipeline2
      state: directory
      mode: 0755
      group: jenkins
      owner: jenkins
    when: my_folder.stat.exists == false


  - name: remove contents in dir if any
    file:
      state: absent
      path: /tmp/django-pipeline2
    ignore_errors: yes

  - name: unflating django source zipfile
    unarchive:
      src: /tmp/artifact.zip
      dest: /tmp/
      creates: /tmp/django-pipeline2
      copy: no
      remote_src: no

  - name: build docker image
    command: sudo docker build -t django-pipeline2-image .
    args:
      chdir: /tmp/django-pipeline2