---
- hosts: ansible
  become: true

  tasks:
  - name: current directory
    shell: pwd
    register: pwd

  - name: copying artifact file to docker host
    shell: scp -i /var/lib/jenkins/Easy-Audit-Keypair.pem artifact.zip jenkins@docker:/tmp/artifact.zip
    